### ISSUE TITLE
Bug trend loading error

### ISSUE THREAD

**Issue by d-ariho** [nbrown02/AzureDevOps-OData-SampleReports#1]
When loading the bug trend.pbit file, I recieved a data source error relating to a null value found in one of the table properties.

![Screenshot (37)](https://user-images.githubusercontent.com/97674085/183122787-fc2f92ca-8963-499c-b213-9d54a5421e31.png)

I found the error in Power Query and was unsure of how to proceed. Would this have to be removed or do the values need to change?

![Screenshot (39)](https://user-images.githubusercontent.com/97674085/183122332-14fb1e0e-68ae-4309-8185-28a33f562b39.png)

**Comment by nbrown02** [comment]
Thanks for reaching out. I wonder what's causing that - unable to replicate it myself. Can you try remove error and see if it will load the data?

**Comment by d-ariho** [comment]
Hi @nbrown02 I have tried removing the data using the remove errors and remove rows selections and the error remains each time. Data is not loading because of this.

**Comment by nbrown02** [comment]
Hmm - I'll have to see if I can replicate this issue. It's something that has never been been raised before...

**Comment by nbrown02** [comment]
@d-ariho - can you give it a try now? I removed the iteration field and think it now works...

**Comment by d-ariho** [comment]
Thank you @nbrown02 - it is working now and data is loading 👍

**Comment by nbrown02** [comment]
Closing this issue as now working :)
